const ScreenNames = {
    splash: 'Splash',
    onboarding: 'Onboarding',
    tabs: 'Tabs',
    auth: 'Auth',
    home: 'Home',
    myWebview: 'MyWebview',
    product: 'Product',
    introProduct: 'IntroProduct',
    news: 'News',
    transactions: 'Transactions',
    topUp: 'TopUp',
    assets: 'Assets',
    help: 'Help',
    login: 'Login',
    confirmOtp:'ConfirmOTP',
    accumulatedAssets: 'AccumulatedAssets',
    account:'Account',
    informationAccount:'InformationAccount',
    convertScreen: 'ConvertScreen',
    packageDetail: 'PackageDetail',
    quickAuthentication: 'QuickAuthencation',
    changePwd: 'ChangePwd',
    bookDetail: 'BookDetail',
    editProfile:'EditProfile',
    inviteFriends:'InviteFriends',
    manual: 'Manual',
    questions: 'Questions',
    paymentMethod: 'PaymentMethod',
    withDrawFromAccount: 'WithDrawFromAccount',
    linkAccount:'LinkAccount',
    cashFlow:'CashFlow',
    loginWithTouchId:'LoginWithTouchId',
    notifiCation: 'Notification',
    setPinCode:'SetPinCode'
};

export default ScreenNames;
